{
 "title": "Douro Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Domain Expiration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(douro_domain_expiration_timestamp - time()) / 86400",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "DNS Resolution",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "douro_dns_resolve_duration_seconds",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "douro_http_status_code", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Domain Information Overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "douro_domain_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TLS Cert Expiration",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(douro_tls_cert_expiration_timestamp - time()) / 86400",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}